name: pip-install-test2

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    name: Testing pip install, updating requirements.txt
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:a
        python-version: ["3.8"]
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install using pip
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e .
    - name: Test on pytest
      run:
        pytest
